version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./api
    ports:
      - "4000:4000"
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
